# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels.  Insight from:  https://github.com/dgrtwo/widyr/blob/master/.travis.yml
      - libudunits2-dev # for ggraph.  Insight from:  https://github.com/dgrtwo/widyr/blob/master/.travis.yml

warnings_are_errors: true

before_install:
 - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

apt_packages:
 - curl # for ldatuning.  Insight from:  https://github.com/nikita-moor/ldatuning/blob/master/.travis.yml
 - libcurl4-openssl-dev # for ldatuning.  Insight from:  https://github.com/nikita-moor/ldatuning/blob/master/.travis.yml

r_binary_packages:
 - topicmodels # for ldatuning.  Insight from:  https://github.com/nikita-moor/ldatuning/blob/master/.travis.yml
 - Rmpfr # for ldatuning.  Insight from:  https://github.com/nikita-moor/ldatuning/blob/master/.travis.yml

r_packages:
 - covr
 
after_success:
 - Rscript -e 'library(covr); codecov()'