# DO NOT CHANGE the "init" and "install" sections below
# Adapt as necessary starting from here

environment:
  R_VERSION: stable
  
build_script:

  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl

test_script:

  - travis-tool.sh run_tests

on_failure:

  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits