

ui <- shiny::shinyUI(
  shiny::navbarPage(title = 'SAoTD', 
                    theme = shinythemes::shinytheme('simplex'),
                    
                    shiny::tabPanel(title = "Correlation Network", fluid = TRUE,
                                    shiny::sidebarPanel(width = 3,
                                                        shiny::sliderInput(inputId = "Correlation",
                                                                           label = "Word Correlation", 
                                                                            min = 0.01, 
                                                                             max = 1.0, 
                                                                             value = 0.15),
                                                          shiny::selectInput(inputId = "layout", 
                                                                             label = "Chart Layout:", 
                                                                             choices = list("star", "circle", "gem", "dh", "graphopt", "grid", "mds", "randomly", "fr", "kk", "drl", "lgl"),
                                                                             selected = "fr"),
                                                          shiny::selectInput(inputId = "edge_color", 
                                                                             label = "Select Edge Color", 
                                                                             choices = list('Grey' = "#999999", 
                                                                                            'Orange' = "#E69F00", 
                                                                                            'Sky Blue' = "#56B4E9", 
                                                                                            'Bluish Green' = "#009E73", 
                                                                                            'Blue' = "#0072B2", 
                                                                                            'Vermilion' = "#D55E00", 
                                                                                            'Reddish Purple' = "#CC79A7")),
                                                          shiny::selectInput(inputId = "node_color", 
                                                                             label = "Select Edge Color", 
                                                                             choices = list('Black' = "#000000",
                                                                                            'Orange' = "#E69F00", 
                                                                                            'Sky Blue' = "#56B4E9", 
                                                                                            'Bluish Green' = "#009E73", 
                                                                                            'Yellow' = "#F0E442", 
                                                                                            'Blue' = "#0072B2", 
                                                                                            'Vermilion' = "#D55E00", 
                                                                                            'Reddish Purple' = "#CC79A7")),
                                                          shiny::sliderInput(inputId = "node_size",
                                                                             label = "Node Siz e:",
                                                                             min = 0.5, 
                                                                             max = 5, 
                                                                             ticks = 1,
                                                                             value = 1),
                                                          shiny::textInput(inputId = "set_seed", 
                                                                           label = "Set Seed", 
                                                                           value = 1234)),
                                      shiny::mainPanel(width = 9,
                                                       shiny::tabsetPanel(
                                                         shiny::tabPanel(title = 'Word Correlation Network',
                                                                         plotOutput(outputId = "TD_Corr_Plot"))))),
                


                  shiny::tabPanel(title = "Bi-Gram Network", fluid = TRUE,
                                  shiny::sidebarLayout(
                                    shiny::sidebarPanel(width = 3,
                                                        shiny::textInput(inputId = "num_bigrams",
                                                                         label = "Number of Bigrams",
                                                                         value = 80),
                                                        shiny::selectInput(inputId = "layout",
                                                                           label = "Chart Layout:",
                                                                           choices = list("star", "circle", "gem", "dh", "graphopt", "grid", "mds", "randomly", "fr", "kk", "drl", "lgl"),
                                                                           selected = "fr"),
                                                        shiny::selectInput(inputId = "edge_color",
                                                                           label = "Select Edge Color",
                                                                           choices = list('Grey' = "#999999",
                                                                                          'Orange' = "#E69F00",
                                                                                          'Sky Blue' = "#56B4E9",
                                                                                          'Bluish Green' = "#009E73",
                                                                                          'Blue' = "#0072B2",
                                                                                          'Vermilion' = "#D55E00",
                                                                                          'Reddish Purple' = "#CC79A7")),
                                                        shiny::selectInput(inputId = "node_color",
                                                                           label = "Select Edge Color",
                                                                           choices = list('Black' = "#000000",
                                                                                          'Orange' = "#E69F00",
                                                                                          'Sky Blue' = "#56B4E9",
                                                                                          'Bluish Green' = "#009E73",
                                                                                          'Yellow' = "#F0E442",
                                                                                          'Blue' = "#0072B2",
                                                                                          'Vermilion' = "#D55E00",
                                                                                          'Reddish Purple' = "#CC79A7")),
                                                        shiny::sliderInput(inputId = "node_size",
                                                                           label = "Node Size:",
                                                                           min = 0.5,
                                                                           max = 5,
                                                                           ticks = 1,
                                                                           value = 1),
                                                        shiny::textInput(inputId = "set_seed",
                                                                         label = "Set Seed",
                                                                         value = 1234)),
                                    shiny::mainPanel(width = 9,
                                                     shiny::tabsetPanel(
                                                       shiny::tabPanel(title = 'Bi-Gram Network',
                                                                       plotOutput(outputId = "TD_Bigram_Plot"))))))))
                        









#  # Correlation Network
#                 shiny::sidebarLayout(
#                   
#                   shiny::sidebarPanel(width = 3,
#                                       shiny::sliderInput(inputId = "Correlation",
#                                                          label = "Word Correlation", 
#                                                          min = 0.01, 
#                                                          max = 1.0, 
#                                                          value = 0.15),
#                                       shiny::selectInput(inputId = "layout", 
#                                                          label = "Chart Layout:", 
#                                                          choices = list("star", "circle", "gem", "dh", "graphopt", "grid", "mds", "randomly", "fr", "kk", "drl", "lgl"),
#                                                          selected = "fr"),
#                                       shiny::selectInput(inputId = "edge_color", 
#                                                          label = "Select Edge Color", 
#                                                          choices = list('Grey' = "#999999", 
#                                                                         'Orange' = "#E69F00", 
#                                                                         'Sky Blue' = "#56B4E9", 
#                                                                         'Bluish Green' = "#009E73", 
#                                                                         'Blue' = "#0072B2", 
#                                                                         'Vermilion' = "#D55E00", 
#                                                                         'Reddish Purple' = "#CC79A7")),
#                                       shiny::selectInput(inputId = "node_color", 
#                                                          label = "Select Edge Color", 
#                                                          choices = list('Black' = "#000000",
#                                                                         'Orange' = "#E69F00", 
#                                                                         'Sky Blue' = "#56B4E9", 
#                                                                         'Bluish Green' = "#009E73", 
#                                                                         'Yellow' = "#F0E442", 
#                                                                         'Blue' = "#0072B2", 
#                                                                         'Vermilion' = "#D55E00", 
#                                                                         'Reddish Purple' = "#CC79A7")),
#                                       shiny::sliderInput(inputId = "node_size",
#                                                          label = "Node Size:",
#                                                          min = 0.5, 
#                                                          max = 5, 
#                                                          ticks = 1,
#                                                          value = 1),
#                                       shiny::textInput(inputId = "set_seed", 
#                                                        label = "Set Seed", 
#                                                        value = 1234)),
#                   shiny::mainPanel(width = 9,
#                                    shiny::tabsetPanel(
#                                      shiny::tabPanel(title = 'Word Correlation Network',
#                                                      plotOutput(outputId = "TD_Corr_Plot"))))),
#                 
#               # Bi-Gram Network
# 
#                 shiny::sidebarPanel(width = 3,
#                                     shiny::textInput(inputId = "num_bigrams",
#                                                      label = "Number of Bigrams",
#                                                      value = 80),
#                                     shiny::selectInput(inputId = "layout",
#                                                        label = "Chart Layout:",
#                                                        choices = list("star", "circle", "gem", "dh", "graphopt", "grid", "mds", "randomly", "fr", "kk", "drl", "lgl"),
#                                                        selected = "fr"),
#                                     shiny::selectInput(inputId = "edge_color",
#                                                        label = "Select Edge Color",
#                                                        choices = list('Grey' = "#999999",
#                                                                       'Orange' = "#E69F00",
#                                                                       'Sky Blue' = "#56B4E9",
#                                                                       'Bluish Green' = "#009E73",
#                                                                       'Blue' = "#0072B2",
#                                                                       'Vermilion' = "#D55E00",
#                                                                       'Reddish Purple' = "#CC79A7")),
#                                     shiny::selectInput(inputId = "node_color",
#                                                        label = "Select Edge Color",
#                                                        choices = list('Black' = "#000000",
#                                                                       'Orange' = "#E69F00",
#                                                                       'Sky Blue' = "#56B4E9",
#                                                                       'Bluish Green' = "#009E73",
#                                                                       'Yellow' = "#F0E442",
#                                                                       'Blue' = "#0072B2",
#                                                                       'Vermilion' = "#D55E00",
#                                                                       'Reddish Purple' = "#CC79A7")),
#                                     shiny::sliderInput(inputId = "node_size",
#                                                        label = "Node Size:",
#                                                        min = 0.5,
#                                                        max = 5,
#                                                        ticks = 1,
#                                                        value = 1),
#                                     shiny::textInput(inputId = "set_seed",
#                                                      label = "Set Seed",
#                                                      value = 1234)),
#                 shiny::mainPanel(width = 9,
#                                  shiny::tabsetPanel(
#                                    shiny::tabPanel(title = 'Bi-Gram Network',
#                                                    plotOutput(outputId = "TD_Bigram_Plot")))))
# 
# 
# 
# 
# 
# # # sidebarPanel(width = 3,
# # #              textInput(inputId = "consumer_key",
# # #                        label = "Consumer Key"),
# # #              textInput(inputId = "consumer_secret",
# # #                        label = "Consumer Secret"),
# # #              textInput(inputId = "access_token",
# # #                        label = "Access Token"),
# # #              textInput(inputId = "access_secret",
# # #                        label = "Access Secret"),
# # #              textInput(inputId = "HT",
# # #                        label = "Hashtag(s)"),
# # #              textInput(inputId = "num_tweets",
# # #                        label = "Number of Tweets"),
# # #              radioButtons("distict", "Choose One:",
# # #                           label = "Distinct Tweets",
# # #                           choiceNames = list(icon("True"), icon("False")),
# # #                           choiceValues = list("True", "False"))
# # # )