---
title: "Stuntz Review of SAoTD"
author: "Sean Stuntz"
date: "March 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SAoTD Package Review
Successfully performed Acquire function per instructions in the Documentation. 

Successfully performed uni, bi, tri gram data analysis and viewed Word Correlation Network.

Successfully veiwed each sentiment plot output, distributions and world map of tweets. 

First impression: After running through the app my first is impression is that you made this a fun method of scraping data from twitter. All of the code works per your documentation. I did notice that the html tables in the documentation were not completely readable when the user's color theme was set to 'Solarized Dark'. A quick change of my theme, however, resolved the issue. Going to inspect for other error outputs next.

Tested violin plot code for incorrect object and mispelled HT_topic and receved errors for both.

Tested Sentiment Score Distribution code. Interestingly, when I don't specify white fill or black color it defaults to that setting. Question, why not just set defaults for this plot and have the user only select the data frame and binwidth? Just a thought. Not an issue. 

When I generated the word correlation network plot I did not see the correlation scale as depicted in your chart.

When I did not have the package 'maps' installed I received the appropriate error.

Are there different methods of determining sentiment? Could you provide a choice of these methods in your Scores function? 

Also, could you explain the topic analysis a bit more in your documentation? I see that there is an intersection of the two grahps at 5 topics but I'm not really sure what to make of it. This is entirely a result of my lack of familiarity with topic analaysis but a brief discussion here could benefit users.

I think the violin plot is awesome and perhaps one of the better outputs of the analysis. It would be interesting to include an option for performing simple means comparisons using the ggpubr::compare_means function which will perform a simple t-test between each of the combinations of pairs and display the p-values on the plot. With five topics that would be cumbersome graphically but if someone reduced the number of topics to three it could be beneficial. Just a thought.

Overall, I think the package lives up to the expectations you lay out in your spreadsheet and the documentation is excellent. 


Overall Grade: Outstanding
